---
bibliography:
- biblio.bib
citation-style: ieee.csl
geometry: "top=3cm, bottom=3cm, left=3cm, right=3cm"
fontsize: 12pt
fontfamily: tgpagella
#fontfamily: times
lang: es-ES
header-includes:
- \usepackage{subfig}
#- \usepackage[ruled,vlined]{algorithm2e}
- \usepackage{fancyhdr}
- \fancyhf{}
- \cfoot{\thepage}
- \pagestyle{fancy}
# Para incluir fichero separado con código LaTeX
#- \input{separators/preamble.tex}
title: Un Trabajo Fin de Grado excelente 
author: Fulanito Pérez Gómez y Gonzalo González Gonzalvo
advisor: Juan Carlos Sáez Alcaide
department: Departamento de Arquitectura de Computadores y Automática
program: Grado en Ingeniería Informática
course: 2022-2023
date: 2023
---